# Generated by Django 4.1.4 on 2022-12-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_product_options_alter_product_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zip',
        ),
    ]
