# Generated by Django 4.1.4 on 2022-12-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('wordpress', 'Wordpress'), ('html', 'HTML'), ('photography', 'Photography'), ('ui', 'UI'), ('mockups', 'Mockups'), ('branding', 'Branding')], default='wordpress', max_length=20),
        ),
    ]
