# Generated by Django 4.1.4 on 2022-12-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_cantact_alter_personalinfo_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cantact',
        ),
    ]
