# Generated by Django 4.1.4 on 2022-12-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
