# Generated by Django 4.1.4 on 2022-12-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_image/concert.jpg', upload_to='profile_Image'),
        ),
    ]
